### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by 19188** [FreedomBen/rtl8188ce-linux-driver#109]
At first,I tired to install the driver,but the terminal said "You are not running the new ***".
Now I work it out.
I found a wrong with " makefile ". In line 3 :"MODDESTDIR := /lib/modules/$(KVER)/kernel/drivers/net/wireless/**rtlwifi**",at first I haven't change it into: "MODDESTDIR := /lib/modules/$(KVER)/kernel/drivers/net/wireless/", then i build failed.but then it change it into,and the terminal said :"You are running the new ***".

Sorry,my English isn't good,I'm Chinese.

**Comment by 19188** [comment]
Maybe it just happend on my computer,but only so i can build success.

**Comment by FreedomBen** [comment]
Glad to hear it worked for you :+1:
