### ISSUE TITLE
Does this driver work with a Realtek RTL8191SEvB Wireless LAN Controller?

### ISSUE THREAD

**Issue by schnappijedi** [FreedomBen/rtl8188ce-linux-driver#115]
Have a RTL8191SEvB Wireless LAN Controller and have had issues with the card since starting to use Linux.

Installed this driver but always got the message that was not using it. Would one be correct in assuming then that this driver does not work with a Realtek RTL8191SEvB?

On a side note this issue was driving me crazy and making Wifi unusable. The solution that fixed everything ended up being turning off WiFi power management (iwconfig to see if it is on). If you are having problems with a Realtek card encourage trying turning off Wifi power management in addition to other steps to resolve.

Still though would have liked to use this driver if it works with this Wifi card.

**Comment by FreedomBen** [comment]
I don't think it works with the RTL8191SEvB, unfortunately
