### ISSUE TITLE
Does it make works the TP-LINK TL-WN722N v2

### ISSUE THREAD

**Issue by Luismi74** [FreedomBen/rtl8188ce-linux-driver#124]
Sorry to bother with this Issue, have spent 2 days looking at forums and all those stuff, made a mistake and bought the version 2 of this thing, heard that the chipset (RTL8188EUS) doesn't work with kali. This could make it work, for monitor mode?

**Comment by FreedomBen** [comment]
I don't think the EUS uses the same codebase, so I highly doubt this driver will work, sorry.

It's probably not helpful now that you've already bought a card, but I have had good success on fedora with the Alfa AWUS036H.  Kali (which is based on debian) probably has an older kernel than fedora, but that card has been around a _long time_ so should work well.
