### ISSUE TITLE
rtl8188ee: fix frequent disconnect problem?

### ISSUE THREAD

**Issue by karenachiketc** [FreedomBen/rtl8188ce-linux-driver#129]
Hi,

I just have 2 questions:
1. Will they prevent my WiFi from disconnecting? With the current(default) driver the wifi disconnects randomly and I've to restart my laptop to be able to use it again.
2. Will they work with Ubuntu 17.10?

PS: This is not an issue. Just want to know.

**Comment by FreedomBen** [comment]
Hi @karenachiketc , for some people, this does help with disconnecting.  If you have problems with disconnecting I would definitely increase your Tx power (see the README for info).  That seems to help.  Also try everything in the troubleshooting section.  It should work fine with Ubuntu 17.10
