### ISSUE TITLE
Suggestion to remove "RT_TRACE" because it is obsolete and has security problems

### ISSUE THREAD

**Issue by Ygor6889** [FreedomBen/rtl8188ce-linux-driver#159]
I suggest the creator of this driver remove everything related to "RT_TRACE" because this line is unnecessary and does nothing except give problems compiling the driver, this line is no longer needed because newer kernels don't need it anymore

**Comment by FreedomBen** [comment]
Thanks @Ygor6889 !

**Comment by trumad** [comment]
I just ran into a build failure because of this. Not quite sure how to fix it, but I'll try removing all "traces" of RT_TRACE

**Comment by trumad** [comment]
Hooray, that worked. I ran the script from scratch, waited until the file rtl8188ee/pwrseqcmd.c existed, removed every call to RT_TRACE from it, and the script continued without issue. Unfortunately my wifi card still stops working intermittently, but that's a separate issue.

**Comment by J0w03L** [comment]
> Hooray, that worked. I ran the script from scratch, waited until the file rtl8188ee/pwrseqcmd.c existed, removed every call to RT_TRACE from it, and the script continued without issue. Unfortunately my wifi card still stops working intermittently, but that's a separate issue.

Ran into the same problem and this worked for me too; thanks!
