### ISSUE TITLE
Not running any rtl8192c_common

### ISSUE THREAD

**Issue by taniadaniela** [FreedomBen/rtl8188ce-linux-driver#63]
Hello, I'm using Elementary Luna, with 3.2.0-75-generic kernel,my wifi card is RTL8188CE, I've installed the driver with the automatic installation, when I run ./am_i_using_this_driver.sh I get this:

__[*] You are running the new rtlwifi__
__[*] Not running any rtl8192c_common__
__[*] You are running the new rtl8192ce__

It's ok that rtl8192c_common is not running?

**Comment by FreedomBen** [comment]
Yep, that's normal for that kernel version.  I'll update that script to help avoid confusion :-)
