### ISSUE TITLE
Super user detection is incorrect sudo problem in Ubuntu

### ISSUE THREAD

**Issue by fruit** [FreedomBen/rtl8188ce-linux-driver#70]
Hi!

Sorry for reporting two issues as single issue. Both problems are very closed to each other ;>

I'm running Ubuntu 14.04 (Xubuntu) and my current building branch is "ubuntu 14.04".

The first problem located in the file [functions.sh#L142](/FreedomBen/rtl8188ce-linux-driver/blob/ubuntu-14.04/functions.sh#L142) ``!=`` should be changed with a ``=``, because ``0`` is a root's UID.

IMHO, the code will look in that way:

        142:  if [ "$(id -u)" = "0" ]; then
        143:      echo "rtl8192ce" >> "$file"
        144:  else
        145:      sudo -u root 'echo "rtl8192ce" >> "$file"'
        146:  fi

The second problem occurs on line [145](/FreedomBen/rtl8188ce-linux-driver/blob/ubuntu-14.04/functions.sh#L145):

    sudo: echo "rtl8192ce" >> "$file": command not found

To execute command without error, I changed it to (perhaps Ubuntu only solution):

    sudo -u root echo "rtl8192ce" >> "$file"

**Comment by fruit** [comment]
New information...

The command sudo w/o single-quotes I've posted, does not works as well.

Also ``sudo echo "rtl8192ce" >> "$file"`` does not work too.

But this variant work good:

    sudo sh -c "echo 'rtl8192ce' >> $file"

**Comment by FreedomBen** [comment]
Thanks!
