### ISSUE TITLE
Compilation fail on branch generic-3.19.x

### ISSUE THREAD

**Issue by Wykks** [FreedomBen/rtl8188ce-linux-driver#72]
Running Fedora 21 with Linux 3.19.3.-200.fc21.x86_64
(For some reason, install.sh tell me to switch to ubuntu 12.04 branch. I choose continue without switching)

Same issue as #58 #64  basically 

To fix the problem, I had to cherry-pick this commit : baa2d6bfe8f91a5dd3b6d8f646f0e3497ff30385

**Comment by FreedomBen** [comment]
Thanks, I'll pick that commit over

**Comment by FreedomBen** [comment]
also lol at suggesting the 12.04 branch :wink:

**Comment by FreedomBen** [comment]
Picked to branch `generic-3.19.x`
