### ISSUE TITLE
Can't connect to Wireless N network.

### ISSUE THREAD

**Issue by x0a** [FreedomBen/rtl8188ce-linux-driver#76]
Iwconfig shows my bit rate as perpetually stuck at 18 megabits/s. I also can't connect to N-only networks (it will just try to connect indefinitely). 

I'm running trusty tahr.
"01:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8188CE 802.11b/g/n WiFi Adapter (rev 01)"
x0a@hplp:~/rtl8188ce-linux-driver$ iwlist wlan0 bitrate
wlan0     unknown bit-rate information.
          Current Bit Rate:18 Mb/s

**Comment by x0a** [comment]
I've figured it out! The problem isn't the driver, it's the router settings. I hadn't suspected the router because the stock driver connected okay, but that is actually incorrect behavior. Wireless N requires WMM support to be enabled in order to allow speeds greater than 54 mbps. WMM and QoS both contribute to the high throughput of Wireless N, thus a lot of devices will refuse to connect to a network under Wireless N if WMM is disabled.  So this is completely normal behavior.

**Comment by FreedomBen** [comment]
Awesome, thank you!
